version: '3.8'

services:
  database:
    container_name: postgresDB
    image: postgres
    volumes:
      - postgres_Database:/var/lib/postgresql/data
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  api:
    container_name: api_container
    image: api_image
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    build:
      context: ./go_work
      dockerfile: multistage.Dockerfile
    networks:
      - mynetwork
  
  frontend:
    container_name: flutterapp
    image: frontend_api
    ports:
      - 1200:80
    build: ./my_form
    networks:
      - mynetwork

volumes:
  postgres_Database:

networks:
  mynetwork:
